reddit/baseplate.py

- baseplate/metrics.py
- tests/unit/metrics_tests.py
socket.sendto() was resolving the name of the statsd server each time we
needed to send a batch of metrics. This was obviously quite slow. By
doing an upfront socket.connect() call, the DNS lookup only happens
once.
Here's what it looked like when I put the IP address instead of hostname
in the configs:
:eyeglasses: @kjoconnor @bsimpson63
> Don't do DNS lookups each time we want to send metrics

- .travis.yml
- baseplate/crypto.py
- baseplate/message_queue.py
- debian/control
- docs/api/baseplate/message_queue.rst
- docs/api/index.rst
- setup.py
- tests/integration/message_queue_tests.py
- tests/unit/crypto_tests.py
This will be helpful for communicating with sidekick processes on the same machine, e.g. events. I'm adding this here first and then moving the event collectors over to this from their SysV IPC queues. Once that's proven out, then the goal is to have r2 and baseplate app servers send messages to the collector via local-system queues and a small daemon, rather than going through Rabbit which is currently getting close to max throughput.
(this also includes a fix for a bug i introduced by trying to be too clever in constant_time_compare. i've made sure the code is identical to r2's copy again. i should've known better, sorry)
:eyeglasses: @bsimpson63 @ketralnis @MelissaCole
> Message queues

- baseplate/crypto.py
This allows applications to inspect the expiration time of an expired
signature.
:eyeglasses: @umbrae @drunken-economist
> crypto: Add expiration time to the ExpiredSignatureError

- baseplate/server/__init__.py
- baseplate/server/einhorn.py
- docs/cli/serve.rst
- tests/unit/server/einhorn_tests.py
- tests/unit/server/server_tests.py
This makes a more clearly defined interface for interacting with Einhorn
and is a little more robust with respect to detecting if we're a child
of Einhorn.
:eyeglasses: @dellis23 @ckwang8128
> Pull Einhorn client code into separate module

- baseplate/context/cassandra.py
Update the docstring fro cluster_from_config to indicate that any kwargs will be  forwarded to the Cluster constructor.
> Update cluster_from_config documentation

- baseplate/server/thrift.py
THeaderTransport detects the protocol of the client and can accept raw
binary protocol (without headers). It's supposed to then use the same
protocol when responding. Because we were using a different instance of
THeaderTransport for the input and output streams, the detected format
was not being used when responding. This lead to binary protocol clients
hanging as they got invalid data in response. This resolves the issue by
using the same transport and protocol instances in both directions.
:eyeglasses: @dellis23 @krishnan-chandra
> thrift: Fix binary protocol responses from header protocol server

- setup.py
This fixes the find_packages() call so we don't install the test suite
as a top-level "tests" package which is pretty messy.
:eyeglasses: @dellis23 @ckwang8128
> debian: Don't install test suite

- baseplate/context/cassandra.py
Looks like we are setting trace=True in all requests because the third argument in Session.execute_async is `trace` rather than `timeout`:
https://github.com/datastax/python-driver/blob/master/cassandra/cluster.py#L2000
> Use kwargs in call to execute_async

- baseplate/core.py
- baseplate/diagnostics/tracing.py
- docs/baseplate/core.rst
- docs/baseplate/diagnostics/index.rst
- docs/words.txt
- tests/integration/tracing_tests.py
- tests/unit/diagnostics/tracing_tests.py
The diagnostics.tracing module adds span recording to Baseplate
via a set of observers for both a request's server span and any
child spans. The observer records spans with the basic annotations
required for simple Zipkin querying and visualization, namely the
client_send, client_receive, server_send, and server_receive
annotations.
TraceSpanObservers set `cs` and `cr` annotations for outgoing request spans, and TraceServerSpanObservers set `sr` and `ss` annotations for inbound requests the service handles.
This first pass does *not* include functionality for adding arbitrary span tags ('binary annotations' in Zipkin language) and is missing some optional endpoint information in the base annotations but both should be pretty straightforward with `on_set_tag` and are coming in followup …
> Add basic Zipkin-compatible tracing observer

- baseplate/context/thrift.py
- baseplate/core.py
- baseplate/diagnostics/tracing.py
- baseplate/integration/pyramid.py
- baseplate/integration/thrift/__init__.py
- docs/words.txt
- tests/integration/pyramid_tests.py
- tests/integration/thrift_tests.py
- tests/unit/core_tests.py
- tests/unit/diagnostics/tracing_tests.py
This adds two features to Baseplate span handling, split across two commits:
1. Add binary annotation generation for on_set_tag events - This is relatively straightforward.
2. Add passing of sampling information and flags in trace information across spans - This adds handling of two more headers for trace information propagation: 
* "Sampled": If this value is present, it communicates whether or not a request has already been deemed to be sampled or not upstream. If not present, we calculate it at the handling service based on a defined sampling rate. For requests that are not sampled, either by our choice or the upstream-defined option, we do not remotely record the span in baseplate via the observer. 
* "Flags": This is a 64-bit integer used as a set of bitflags for feature flagging …
> Add binary annotations and span sampling + flags

- .travis.yml
- Makefile
- baseplate/config.py
- baseplate/diagnostics/tracing.py
- baseplate/events/__init__.py
- baseplate/random.py
- baseplate/service_discovery.py
- docs/baseplate/config.rst
- docs/baseplate/random.rst
- docs/baseplate/service_discovery.rst
- docs/config_example.ini
- docs/index.rst
- docs/words.txt
- manifests/init.pp
- setup.cfg
- tests/integration/pyramid_tests.py
- tests/integration/tracing_tests.py
- tests/unit/config_tests.py
- tests/unit/random_tests.py
- tests/unit/service_discovery_tests.py
(definitely go commit-by-commit on this one. It's not so bad, but the overall diff is unnecessarily daunting)
The core of this pull request is a module that can read and understand synapse-generated JSON service inventories. This is needed for the upcoming websocket auto-discovery stuff (IO-1056) and potentially down the line for things like Cassandra clients.
I intend to replace `r2.lib.utils.weighted_lottery` with the implementation here to further standardize.
The `config.File` parser came up in both authn and thing services, so it felt like a good time to get it in here.
While doing this work, I ran into some issues with tests and some cleanliness issues that pyflakes in my editor caught but `make lint` (and therefore CI) didn't; so I've cleaned those up and switched that lint step …
> Synapse file_output integration, config.File, and some cleanup

- baseplate/core.py
- baseplate/diagnostics/tracing.py
Add passing optional settings to the tracing observer via `configure_tracing`. This also fixes a few minor bugs:
* Client event annotation tags were mixed up
* Include binary annotations being sent everywhere. 
> Add settings to configure_tracing and fix client annotations

- baseplate/_compat.py
- baseplate/context/cassandra.py
Currently we get errors like this when you use a Statement class rather than a string for the query and you have tracing enabled:
```
TypeError: <SimpleStatement query="SELECT * FROM table_name", consistency=Not Set> is not JSON serializable
```
> Handle Cassandra Statement queries in statement tag

- baseplate/diagnostics/tracing.py
- tests/unit/diagnostics/tracing_tests.py
Zipkin doesn't like non-string/boolean values for binary annotations, per 
https://github.com/openzipkin/zipkin/issues/1372
and changes introduced in 
https://github.com/openzipkin/zipkin/pull/1269
https://github.com/openzipkin/zipkin/commit/3b8d56ac1b817729517e32c7a3d311b7ceaa2fb7#diff-b603d520f1c771c817602413216dd6c3L191
Based on discussions in the above, the general approach is to coerce numerical values to strings. I'm choosing to do this directly at the baseplate tracing serialization level as a defensive measure. 
:eyeglasses: @bsimpson63
> Force string coercion for binary annotation values

- baseplate/context/__init__.py
- baseplate/context/sqlalchemy.py
- baseplate/core.py
- baseplate/diagnostics/metrics.py
- baseplate/diagnostics/tracing.py
- baseplate/integration/__init__.py
- baseplate/integration/wrapped_context.py
- tests/integration/pyramid_tests.py
- tests/integration/sqlalchemy_tests.py
- tests/unit/context/tests.py
- tests/unit/core_tests.py
- tests/unit/diagnostics/tracing_tests.py
This adds baseplate support for tracing local in-request spans. It adheres to the "spec" outlined in the following:
https://github.com/openzipkin/zipkin/issues/808
https://github.com/openzipkin/zipkin/pull/821
This interface is intended to be able to generate local spans in various contexts from the main server span. The differences in serialization, use case, and explicit annotations (or lack thereof) were enough for me to lean towards making a new observer and API to specifically handle local spans. This allows us the freedom to customize Baseplate local spans as we see fit moving forward, e.g. force all local spans to carry certain tags, etc.
> Add support for local spans in tracing

- baseplate/diagnostics/tracing.py
urllib3.connectionpool is the underlying module backing
connection pools that are created for Zipkin connections.
There are spammy INFO-level connection logs that should
be suppressed.
This is for https://reddit.atlassian.net/browse/IO-1855
Do we want to do this more generally anywhere? This seemed reasonable to me since this tracing module might be used standalone. 
> Suppress noisy urllib3 INFO logging.

- README.rst
- docs/baseplate/core.rst
- docs/requirements.txt
- setup.py
This allows the build process to be automated without giving
write-access credentials to CI. Additionally, it lets us have multiple
versions of docs live for when multiple releases are around.
Also a quick place I missed while doing the sentry stuff that I noticed
while doing this.
> Switch to ReadTheDocs for documentation

- baseplate/__init__.py
This allows dev installs to not report anywhere cleanly.
(Caught this while prepping the cookiecutter upgrades for this release)
> Make Sentry DSN optional

- baseplate/diagnostics/sentry.py
This allows correlation of errors with logs and other tools, and might
be helpful when looking at how errors propagate across the system.
> Add trace ID to sentry context

- baseplate/context/__init__.py
- baseplate/core.py
- baseplate/integration/wrapped_context.py
- tests/integration/pyramid_tests.py
- tests/unit/context/tests.py
- tests/unit/core_tests.py
Wrapped contexts for local spans need to support shadowing
currently existing context attributes for substitution in certain
situations like within a local span as well as adding/overriding
attributes of the underlying context for developer ease. The single
setattr override in WrappedRequestContext could not do shadowing
properly on its own since it would always modify the underlying context directly 
if the attribute existed. Since shadowing should only happen within
Baseplate-specific integration code (application developers should
not need this capability directly as they shouldn't be modifying
Baseplate-added context attributes themselves), WrappedRequestContext
utilizes the standard setattr interface to access the underlying
context. This adds an explicit method to shadow attributes …
> Add explicit shadowing method for wrapped context attributes.

- baseplate/metrics.py
- tests/unit/metrics_tests.py
This seems like an anti-feature of gauges since we can't trust that the
"current" value is stable in the face of statsd restarts.
> Remove gauge increment/decrement

- baseplate/__init__.py
- baseplate/config.py
- baseplate/secrets/fetcher.py
- baseplate/secrets/store.py
- docs/baseplate/config.rst
- docs/config_dictof_example.ini
- docs/config_dictof_spec_example.ini
- tests/unit/config_tests.py
This is useful for less static configuration, stuff that's closer to
data than basic configuration, which will likely be much more common
when we get live configuration abilities in Baseplate.
See the included docs for an example of usage.
I'm concerned about this parser being confusing since it takes multiple
keys instead of a single one. Maybe there's a better name than `DictOf`?
Maybe it'd be better to do a more complex syntax like requiring the key
in the config dict to be something like `"key.*": config.DictOf(...),`?
> Add DictOf config parser

- baseplate/diagnostics/tracing.py
This contains two fixes for tracing-related exceptions so errors are handled more gracefully within Baseplate to avoid breaking services that enable tracing instrumentation. 
> Tracing exception handling

- docs/conf.py
They're pretty cluttered and not bringing much to the table. Some of the
longer titles are starting to mess with layout.
Before:
After:
> Remove navigation links from the sidebar

- baseplate/_compat.py
- baseplate/diagnostics/metrics.py
- baseplate/experiments/__init__.py
- baseplate/experiments/providers/__init__.py
- baseplate/experiments/providers/base.py
- baseplate/experiments/providers/feature_flag.py
- baseplate/experiments/providers/forced_variant.py
- baseplate/experiments/providers/r2.py
- docs/baseplate/experiments/feature_flag.rst
- docs/baseplate/experiments/forced_variant.rst
- docs/baseplate/experiments/index.rst
- docs/baseplate/experiments/r2.rst
- docs/index.rst
- docs/words.txt
- tests/integration/tracing_tests.py
- tests/unit/diagnostics/tracing_tests.py
- tests/unit/experiments/experiment_tests.py
- tests/unit/experiments/providers/feature_flag_tests.py
- tests/unit/experiments/providers/forced_variant_tests.py
- tests/unit/experiments/providers/r2_tests.py
This update ports the feature flag and experiment code from [r2](https://github.com/reddit/reddit/tree/master/r2/r2/config/feature) and their tests into baseplate.  Rather than just doing a straight port, this change attempts to:
1. Define a new, more extensible config format
2. Support for different experiment "providers" that can have different config formats and bucketing logic.
3. Formally separate feature flags from experiments
4. Remove un-used bits of code
> Add experiments and feature flags

- baseplate/diagnostics/tracing.py
- tests/integration/tracing_tests.py
- tests/unit/core_tests.py
Per spec, child spans can be created within local spans, so local span
observers need to have a listener for that event and make sure
the child spans made within local spans are instrumented accordingly.
I think this bug got introduced with the restructuring of the span hierarchy. Since we need to differentiate the local vs non-local child span case, I've duplicated the method in the two subclasses of TraceSpanObserver (`TraceLocal` and `TraceServer`); an intermediate subclass would remove some duplicate code but I wanted to avoid adding complexity to the hierarchy for this small need. There might also be a need in the future to do more differentiating of handling child span creation in server vs local spans. 
:eyeglasses: @spladug @pacejackson
> Add on_child_span_created listener to TraceLocalSpanObserver

- baseplate/experiments/__init__.py
- baseplate/experiments/providers/base.py
- baseplate/experiments/providers/r2.py
- tests/unit/experiments/experiment_tests.py
- tests/unit/experiments/providers/feature_flag_tests.py
- tests/unit/experiments/providers/r2_tests.py
1. Allow non-string override values.
2. Handle `newer_than` correctly.  Should only check `newer_than` as a part of checking the `logged_id` targeting value.
3. Check overrides before checking the bucket_val.
4. Update the bucketing logic to better match what we do in r2.
1. Remove `get_event_type` from experiments.
2. Cache the parsed `Experiment` objects in the `Experiments` client object.
3. Add tests for the fixes.
> Experiment framework fixes and updates

- baseplate/context/redis.py
- docs/baseplate/context/redis.rst
- tests/integration/redis_tests.py
This offers an alternative `MessageQueue` handler that takes a Redis
pool and uses it for backing of the queue storage as opposed to the
POSIX system used normally.
Pros:
* Increased limits for queue size
* Some mechanism to back the queue up to disk (configuration dependent)
* No maximum limit for messages and message size
* No restriction on queue name (even supports empty strings as a key)
Cons:
* Blocking timeout behavior for reads is more restrictive
(it uses the [`BLPOP`](https://redis.io/commands/blpop) which only allows
integers for the seconds based timeout)
* More overhead before a timeout is issued compared to the POSIX variant
> Add in alternative MessageQueue backed by redis

- .travis.yml
- baseplate/context/thrift.py
- baseplate/core.py
- baseplate/integration/pyramid.py
- baseplate/integration/thrift/__init__.py
- docs/baseplate/core.rst
- setup.py
- tests/integration/pyramid_tests.py
- tests/integration/thrift_tests.py
- tests/unit/core_tests.py
Adds wrappers and handlers for retrieving propagated authentication information from upstream requests into an easy to use interface and standard system for further downstream propagation.  Overall the process is to convert the JWT payload received from the authentication service into an `AuthenticationContext` which can do validation and extraction, then store this is the current context and downstream requests via the built in thrift context will pull this value out of the current context and store the necessary information in a standard way for downstream services to easily and automatically retrieve.
There are some assumptions that may need to be refined, such as the way that the public RSA key for the authentication service is stored and retrieved, currently it is assumed (and …
> Authentication context propagation

- baseplate/experiments/__init__.py
- baseplate/experiments/providers/__init__.py
- baseplate/experiments/providers/feature_flag.py
- baseplate/experiments/providers/r2.py
- tests/unit/experiments/experiment_tests.py
- tests/unit/experiments/providers/feature_flag_tests.py
- tests/unit/experiments/providers/forced_variant_tests.py
- tests/unit/experiments/providers/r2_tests.py
Add some new fields:
1. version - a string to be passed along with bucketing events
2. start_ts - epoch timestamp float of the time to start the experiment
3. stop_ts - epoch timestamp float of the time to stop the experiment
Deprecate some existing fields:
1. expired - replaced with start_ts and stop_ts.
> Add some new experiment fields

- baseplate/context/thrift.py
- baseplate/core.py
- baseplate/experiments/__init__.py
- baseplate/integration/pyramid.py
- baseplate/integration/thrift/__init__.py
- baseplate/thrift/baseplate.thrift
- docs/baseplate/core.rst
- docs/words.txt
- tests/integration/pyramid_tests.py
- tests/integration/thrift_tests.py
- tests/unit/core_tests.py
- tests/unit/experiments/experiment_tests.py
- tests/unit/experiments/providers/feature_flag_tests.py
- tests/unit/experiments/providers/r2_tests.py
Provide a framework for passing context data about requests made to edge services between baseplate services.
1. Create Thrift structs to model the request context data.
2. Automatically initialize the `EdgeRequestContext` object from Thrift/HTTP headers.
3. Automatically attach the `Edge-Request` header to thrift requests when using the `PooledClientProxy` client object.
4. Integrate the new `User` and `EdgeRequestContext` objects into the Experiment framework.
NOTE:
This update depends on new fields being added to the AuthenticationContext token.  Currently I have stub functions for these new fields.
> Request context

- baseplate/core.py
- tests/unit/core_tests.py
When I added some basic validation to the `loid_id` field in `EdgeRequestContext.create` I accidentally made it so you could not set `loid_id=None`.  This fixes that and adds a test for that base case.
> Allow loid_id=None in EdgeRequestContext

- baseplate/integration/pyramid.py
- docs/words.txt
- tests/integration/pyramid_tests.py
Currently, the behavior of the baseplate/pyramid integration
is to handle all exceptions raised. This includes those used as
control flow and intended to be caught by an pyramid exception
view.
This is due to the ordering of the tweens. Here's the current
ordering of tweens, with pyramid's nomenclature in parens:
1. Request ingress (`tweens.INGRESS`)
2. Exception view (`tweens.EXCVIEW`)
3. baseplate tween
4. App handler code (`tweens.MAIN`)
Each tween wraps the one beneath it. Since baseplate is wrapping
the handler code, exceptions get caught by it, reraised, and
then caught by the exception view tween.
This is problematic because it has the effect of calling
`finish` on the server span too early, which triggers all the
observers' `on_finish` callbacks. When we have exceptions or
metrics …
> Change baseplate tween position

- baseplate/events/publisher.py
The previous check didn't work properly because requests.Response has
`__bool__` defined as "Returns True if `status_code` is less than 400."
which meant that it was always falsey in the situations we wanted to
check it. Instead, we now just explicitly check if it's `None` and crash
on validation failure. This will discard the current message batch and
upstart will restart us to carry on with further messages.
cc @robdmac since this was biting you on staging the other day.
> Don't retry publishing forever when v2 event fails to validate

- baseplate/integration/pyramid.py
- docs/baseplate/integration/index.rst
- tests/integration/pyramid_tests.py
Right now, there's not really a step between Baseplate running it's initialization on the Pyramid Request object and the service handling the request which makes it difficult to run code that you want to run before each request but after Baseplate has attached the client objects to the requests (say authenticating the request with a thrift service).
With this change, Baseplate will emit an event after it creates the ServerSpan for the request that services can add subscribers to in order to run code like this.
> Emit an event to Pyramid after creating the ServerSpan

- bin/baseplate-script
- bin/baseplate-serve
Using /usr/bin/env python instead of the direct system Python
for Baseplate-included scripts makes Baseplate more friendly
for virtualenv-based and other isolated environment installs.
> Use /usr/bin/env python for Baseplate scripts

- baseplate/thrift_pool.py
I forgot to implement this despite documenting it.
> Fix kwargs usage in thrift_pool_from_config

- baseplate/metrics.py
- docs/baseplate/metrics.rst
- docs/index.rst
- docs/words.txt
- tests/unit/metrics_tests.py
This adds a simple histogram interface to Baseplate metrics.
Our implementation sends simple values as timer stats to the StatsD
backend, expecting the backend to be configured to aggregate
and store histograms, e.g. [Statsite](https://github.com/statsite/statsite/blob/master/README.md#architecture) (Search "histograms"). 
Histograms on top of timers is currently
in both etsy's StatsD implementation as well as Statsite, and anyone trying to use
this with a backend that doesn't have histograms configured will just be sending arbitrary timer values. 
Even though this is just a simple wrapper around timers, I think the 
Histogram abstraction is worth adding. 
> Add a histogram interface to Baseplate's metrics support

- baseplate/diagnostics/metrics.py
- baseplate/metrics.py
- tests/unit/metrics_tests.py
There has been an ongoing conversation in https://reddit.atlassian.net/browse/IO-2820 asking for error counts. This exists for the clients, this PR should add them for the server spans as well.
> Add failure counter for server spans

- baseplate/secrets/fetcher.py
While you generally want to run the secret fetcher as a daemon so it will pick up any updates, there are some situations where you only want to run it once.  This PR adds a `--once` argument to `secret_fetcher.py` that allows you to run it a single time and then exit.
> Allow you to run the secret-fetcher as a script rather than a daemon

- baseplate/core.py
- baseplate/experiments/__init__.py
- baseplate/experiments/providers/r2.py
- tests/unit/core_tests.py
- tests/unit/experiments/experiment_tests.py
- support for firing exposure events
- support for validating experiment names (to differentiate between when `variant` returns null because not bucketed, or "invalid" experiment name
- support for getting a list of all experiment names. This will be used to bucket a user for all (valid) experiments in order to return the full list of variants in a single call.
- fix weird bucketing issue with very small bucketing percentages on r2 experiments
- replace `event_queue` with `event_logger`
> Exposure events

- baseplate/diagnostics/tracing/publisher.py
- tests/unit/diagnostics/tracing/publisher_tests.py
While making changes to the baseplate puppet module I realized I made a
few mistakes in the final round of changes in trace sidecar PR. I wanted to set
them straight before the next version of baseplate is officially
released.
These changes include:
* Renaming the config section from "tracing-publisher" to "trace-publisher". This is more in line with the existing Event publisher config section.
* Remove all Zipkin scheme and API version settings. Instead rely on the ``zipkin_api_url`` config option.
👓 @spladug
> Simplify trace publisher config

- baseplate/thrift_pool.py
- tests/unit/thrift_pool_tests.py
This commit modifies `ThriftConnectionPool._acquire` in order to put a blank (`None`) connection entry back in pool if the retry policy is exhausted while trying to connect to the host.
Previously, one connection pool slot would be lost each time `_acquire` failed to secure a new connection to the host which could eventually drain the connection pool size to zero.
> Ensure that connection failures do not deplete ThriftConnectionPools.

- Makefile
See [here](https://jondavidjohn.com/linux-vs-osx-the-cp-command/).
> Fix build on BSD

- baseplate/experiments/__init__.py
- tests/unit/experiments/experiment_tests.py
Make it so that if a bad config is pushed, the parse_experiment call won't throw an exception to the caller.
> Stop error on bad config

- baseplate/core.py
- baseplate/integration/pyramid.py
- baseplate/integration/thrift/__init__.py
- tests/integration/pyramid_tests.py
- tests/integration/thrift_tests.py
Add support for B3 trace headers whil continuing to support the old
trace headers. This change aims to allow both both B3 and the old
headers to be used as long as they contain identical values. For
example:
```
X-Trace: 1234567890
X-B3-TraceId: 1234567890
```
Fixes #187
> 187 B3 Headers Support

- baseplate/context/__init__.py
- baseplate/context/sqlalchemy.py
- tests/integration/sqlalchemy_tests.py
- tests/unit/context/tests.py
I've always been bothered by the threadlocals I used to make the SQLAlchemy integration work. Digging through their docs again I found that `execution_options()` on an `Engine` creates a new engine that's related to the original but can carry some extra state along with it. This allows us to build nested engines that carry span state!
Unfortunately, while testing that local spans now worked with SQLAlchemy I also discovered that local spans weren't generating context-attributes at all! We were still using the ones from the the server span always. This was because the observer wasn't really set up right. I've fixed that as well.
Hopefully this will also fix the issues the Thing service has been seeing with "SQLAlchemy sessions cannot be used concurrently" errors.
Fixes #99
> Rework SQLAlchemy instrumented client to not use threadlocals

- baseplate/core.py
- baseplate/diagnostics/sentry.py
This can occur when the framework surrounding application code crashes.
For example, when Thrift tries to serialize invalid data like an
1,000,000 in an I16. Without this error reporting it's very annoying to
debug what's going on.
By hooking into the gevent hub, we're tied to using gevent but we
already expect that in Baseplate. This should catch all unhandled
exceptions and give us visibility into them.
cc: @bsimpson63
> Catch exceptions that happen outside server span context

- .travis.yml
- setup.cfg
These creds are just for demonstration purposes. If there is an
organizational PyPI account to use or if one of the listed Baseplate
maintainers wants to supply theirs, let's talk!
The hope here is to do smaller incremental releases and publish them to
PyPI. This would allow Reddit projects that are using wheels to make use
of new functionality and bug fixes before doing a fleetwide release.
@spladug, any help you could lend with the credentials would be much
appreciated.
> Automate PyPI Release

- baseplate/experiments/__init__.py
- tests/unit/experiments/experiment_tests.py
pass span to the logger to improve observability
> add span to output from experiment call

- baseplate/experiments/__init__.py
Local spans in variant calls within the experiments are a massive drain on CPU resources on the high volume of variant calls and provide very little value in this context.
This PR removes them from the 0.28 release (similar commits will remove them from all existing releases; the corresponding commit on master will be linked here once it's up).
> Remove local span on variant call

- baseplate/experiments/__init__.py
Creation of local spans on variant() calls leads to a lot of CPU resource usage, and provides no value at present.
> Remove local span creation on variant call

- baseplate/context/thrift.py
- baseplate/integration/thrift/__init__.py
- tests/integration/test.thrift
- tests/integration/thrift_tests.py
- tests/unit/context/thrift_tests.py
Thrift exceptions defined in the IDL are effectively another form of
return value and should not be considered an RPC failure. If
applications wish to monitor rates of specific (expected) error types
they can do so themselves.
This should allow easier monitoring of error rates.
I wanted to define some proper tests for this when getting it in place and found that the test suite was really not in a good place to do that. So I took the opportunity to rewrite it to allow full end-to-end integration testing of our Thrift integrations. Coverage on existing code is increased.
The first commit was done because 1) it was asked of me in the review for the Apache Thrift code and I hadn't done it yet, and 2) it allowed decoupling some of the tests a bit better.
The final commit (the functional …
> Don't report expected Thrift exceptions as errors to span observers

- baseplate/integration/pyramid.py
- baseplate/integration/thrift/__init__.py
- tests/integration/thrift_tests.py
46db4cd60d8aebbe7c25ea1a7343dbea3f8fdbf1 introduced a bug where we would
throw out traces that didn't have the Sampled header even though it was
optional (and our own client only sends it if non-null).
:eyeglasses: @cshoe @bsimpson63 @ckwang8128
> Don't throw out traces missing optional Sampled header

- .travis.yml
- baseplate/secrets/fetcher.py
- puppet/modules/vault/manifests/init.pp
A [change in vault 0.9.0 removed the nonce from responses where it was not needed](https://github.com/hashicorp/vault/commit/30aab2aa2feff6dd81ca379f2489132ff5bc284a) in order to avoid logging it. I've added nonce generation to the secret fetcher so that vault doesn't make one and log it for us. I also added a bit of documentation to aid in debugging.
> Vault 0.9.0 compatibility

- .travis.yml
We're set up to only deploy to PyPI on tagged commits, however we only
run Travis on commits to master. Our deploy scheme is to push to master
and then gather commits into a release branch. Then we tag the release.
This means we'll need to have travis run on the release branches as
well.
> Get travis auto deploying to PyPI.

- baseplate/experiments/__init__.py
- tests/unit/experiments/experiment_tests.py
When adding the `timeout` parameter to the `FileWatcher`,  we missed updating the `Experiments` client to support it.
> Add FileWatcher 'timeout' to Experiments

- baseplate/integration/pyramid/__init__.py
- baseplate/integration/pyramid/csrf.py
- tests/unit/integration/pyramid/csrf_tests.py
Add `TokenCSRFStoragePolicy` to the pyramid integration.  This is only added if the installed version of pyramid has the `ICSRFStoragePolicy` interface available.
Rather that storing the token in another place and comparing the stored token to what is returned, this simply checks that the token that is sent matches what we would expect based on the request.
> Add 'TokenCSRFStoragePolicy'

- baseplate/crypto.py
The standard library function hmac.compare_digest requires that both
parameters are of the same type (str/unicode/bytes). We did not enforce
that here in Baseplate's shim which makes upgrading harder.
> Add type warning to constant_time_compare shim

- baseplate/context/thrift.py
In some python implementations, e.g. pypy6-3.5, calling
_enumerate_service_methods on thrift classes will also return magic
methods, e.g. "__new__". If we don't filter them out, they will be
replaced by our pooled thrift proxy method, which relies on the
constructor to be called first, but python calls __new__ before the
constructor, so that will cause us troubles.
This should be a no-op for python implementations that does not return
magic methods in the first place.
> thrift: Filter out magic methods from proxy methods

- baseplate/core.py
- baseplate/integration/pyramid/__init__.py
- baseplate/server/metrics.py
- baseplate/server/thrift.py
- baseplate/server/wsgi.py
Baseplate servers will now report concurrent in-flight requests as a
per-hostname-per-PID gauge every 10 seconds if metrics are configured.
The metrics system should handle aggregation appropriately.
:eyeglasses: @ckwang8128 @bsimpson63
> Add concurrency monitoring gauges sent periodically

- baseplate/integration/thrift/__init__.py
- tests/integration/thrift_tests.py
There is currently no official spec for Thrift header
case-sensitivity. This follows Pyramid's approach of storing
HTTP headers in case-insensitive dictionary with Thrift
headers to be lenient in accepted header values while
still propagating headers in the format that they came in.
For reference:
The Pyramid implementation details - https://github.com/Pylons/pyramid/blob/c02f228b554d636d475ad1f34945fd91e4b1bfdf/docs/narr/webob.rst (see `req.headers`) 
The requests CaseInsensitiveDict module - https://github.com/kennethreitz/requests/blob/v1.2.3/requests/structures.py#L37 
The fbthrift header object - https://github.com/apache/thrift/blob/66a44c5d8d57bd0c2e2afd228a29b5bc679a6770/lib/py/src/transport/THeaderTransport.py#L96
> Be case-insensitive with Thrift headers

- baseplate/diagnostics/tracing/__init__.py
Getting a lot of cassandra zipkin pool is busy connection error. Increasing max span batch per this:
https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/p3CwOL0kNrs
@cshoe @ckwang8128
> diagnostics/tracing: inc RemoteRecorder max_span_batch to 100

- baseplate/integration/wrapped_context.py
AFAICT this was not meant to be a public interface and was instead for
the WrappedRequestContext to do its own internal logging that no longer
is done.
:eyeglasses: @bradengroom @ckwang8128
> Remove vestigial logger on context

- baseplate/server/__init__.py
Fixes https://github.com/reddit/baseplate.py/issues/245.
Tested with versions 4.0.0 and 6.5.0.
> Fix baseplate-tshell for versions of ipython 5+

- baseplate/server/__init__.py
This only kicks in when IPython isn't available, but it gives much nicer
keyboard movement when editing text.
Fixes #240
Before, when hitting Ctrl+A to move to the beginning of the line:
```
Baseplate Interactive Shell
Python 3.7.3 (default, Mar 26 2019, 00:55:50) 
[GCC 7.3.0]
Available Objects:
app          This project's app instance
context      The context for this shell instance's span
>>> foo^A^A^A
```
afterwards the cursor just moves.
> Activate readline in baseplate-tshell

- setup.py
This bases versions entirely off of git tags in our case so we never
need to update the source code with version changes again.
setuptools_scm is "the blessed package" for doing this (it's provided by the pypa org who are the main python packaging people). Here's the PEP-440 compliant versioning scheme: https://github.com/pypa/setuptools_scm#default-versioning-scheme
For us, this means that on tagged commits we get a version like `0.30.0` while between releases we get a version like `0.29.1.dev27+ga5f929e` (it increments the last version component and adds the dev suffix including distance from the tagged commit and short commit id).
:eyeglasses: @ckwang8128 @bsimpson63 @pacejackson
> Use setuptools_scm to determine version

- baseplate/context/sqlalchemy.py
- docs/baseplate/context/sqlalchemy.rst
- tests/integration/sqlalchemy_tests.py
- tests/unit/context/sqlalchemy_tests.py
This allows us to specify the different connection params and fetch the password from a SecretsStore.
👓 @spladug @bsimpson63
> Add engine_from_config to sqlalchemy integration

- baseplate/context/cassandra.py
- tests/integration/cassandra_tests.py
Switching from composition to monkeypatching. `execute_concurrent_with_args` uses the `ResponseFuture` returned by our `session` object so that object needs to behave like a regular `ResponseFuture` object.
I added a test that actually executes `execute_concurrent_with_args` and have tested out the code locally in thing service (by copying baseplate/context/cassandra.py into thing and importing it).
👓 @spladug @pacejackson
> Monkeypatch ResponseFuture.result() to wait for callbacks

- baseplate/experiments/targeting/tree_targeting.py
when targeting on strings and attempting to match a long integer,
a TypeError can be thrown. In those cases, catch it and treat as
a non-match.
> catch TypeError in experiment targeting and treat as non-match

- baseplate/thrift/baseplate.thrift
There's no way to specify java namespace to thrift compiler command,
line, and without proper java namespace the generated java code will be
kinda unusable, especially when this file is imported by other thrift
files.
The added java namespace should be a no-op for non-java thrift compiler
actions.
> Add java namespace to baseplate.thrift

- baseplate/integration/pyramid/__init__.py
- tests/integration/pyramid_tests.py
I added a print statement to L221 of baseplate/integration/pyramid/__init__.py and confirmed that the header is always a unicode object by the time it gets there in both Py2.7 and Py3.7. I don't know why I did this with a byte string, other than potentially stupidly mimicing the `.decode("utf8")` that was there before my change. That apparently was an unnecessary no-op.
This should fix #278 by properly parsing the header.
cc: @suzie-su
> Expect 'sampled' header to be unicode already

- baseplate/secrets/__init__.py
- docs/baseplate/secrets.rst
While prepping for 0.30 release, I noticed that the `CredentialSecret` link here is dead. The class needed to be added to the sphinx docs. 
https://baseplate.readthedocs.io/en/latest/baseplate/secrets.html#baseplate.secrets.SecretsStore.get_credentials
> Add CredentialSecret class to documentation

- .drone.yml
- Makefile
- baseplate/metrics.py
- baseplate/server/wsgi.py
- docs/conf.py
- requirements-docs.txt
- requirements-lint.txt
- setup.cfg
This adds the basic requirements and makefile infrastructure for running mypy on baseplate.py. The metrics module is the first ~victim~ place to get annotated up. Sphinx will now pull in type annotations instead of having to do it manually in the docstring. I've also made mypy spit out an HTML report that looks like this:
which should help us track our progress on typing everything up.
Notes:
* We're targeting Python 3.6 so we can't use `from __future__ import annotations` so in places that need forward declarations of types, we just use strings. This feels double plus ungood.
* I've turned off all failed import warnings. Maybe this is too broad and I should explicitly turn off the ones we don't have? flake8/pylint will warn us of true typos though.
* None of the strictness settings are …
> Add mypy infrastructure and type up the metrics module

- baseplate/server/__init__.py
This signal is sent by Einhorn to indicate a shutdown. By listening to
it, we can ask the server to gracefully shut down and properly wait for
existing requests to finish up. This should hopefully help a bit with deploy-related
request failures. 
I have no idea why I didn't do this in the first place. I clearly knew SIGUSR2 was reserved for this purpose. :cry: 
:eyeglasses: @bsimpson63 @pacejackson
> Trigger graceful shutdown of server on SIGUSR2

- baseplate/__init__.py
- baseplate/_utils.py
- baseplate/config.py
- baseplate/core.py
- baseplate/crypto.py
- baseplate/file_watcher.py
- baseplate/random.py
- baseplate/retry.py
- baseplate/secrets/store.py
- baseplate/server/einhorn.py
- baseplate/service_discovery.py
- docs/baseplate/crypto.rst
- setup.cfg
- tests/unit/crypto_tests.py
- tests/unit/file_watcher_tests.py
This brings us from 32% "imprecise" to 28%. Progress.
I'm not super happy with all of this and it definitely shows places where it's really hard to type stuff because it's nice and dynamic. We'll basically never get to have strict types for the request/context object. Bummer.
:eyeglasses: @pacejackson @bradengroom
> Add a bunch of type annotations to a bunch of modules

- baseplate/metrics.py
- tests/unit/metrics_tests.py
The first commit tries to clarify error messaging around metrics batches. I was watching the thing service logs yesterday and noticed a fair number of the "batch too big" warnings were actually for other stuff like "connection refused". I think this also makes the error handling a bit cleaner. The new messaging looks like:
```
Metrics batch of 370109 bytes is too large to send, flush more often or reduce amount done in this request. Top counters: example_service.busy_counter=2345, example_service.normal_counter=37
```
or 
```
Failed to send metrics batch: [Errno 111] Connection refused
```
The second commit fixes an error encountered by the data team in the event collectors.
> Metrics error handling and bugfix

- baseplate/context/__init__.py
- baseplate/context/sqlalchemy.py
- baseplate/context/thrift.py
- baseplate/core.py
- baseplate/server/runtime_monitor.py
- baseplate/thrift_pool.py
- docs/baseplate/context/sqlalchemy.rst
- docs/baseplate/context/thrift.rst
- docs/cli/serve.rst
This adds a new ability to ContextFactory objects that hooks them into
the server runtime metrics system and asks them to periodically produce
metrics.
The SQLAlchemy and Thrift context clients are now instrumented to
periodically report their connection pool statistics to give more
insight into what's going on in there.
For some simple context clients like this:
```python
baseplate.add_to_context(
"downstream", ThriftContextFactory(thrift_pool, BaseplateService.Client))
baseplate.add_to_context("db", SQLAlchemyEngineContextFactory(engine))
```
The following metrics might be sent:
```
example_server.runtime.hostname.PID13814.clients.downstream.size:10|g
example_server.runtime.hostname.PID13814.clients.downstream.checkedout:0|g
example_server.runtime.hostname.PID13814.clients.db.size:5|g …
```
> Collect connection pool statistics periodically

- baseplate/queue_consumer.py
- tests/unit/queue_consumer_tests.py
Currently we are using the default value which is unbounded.  In certain cases, this can lead to the _ConsumerWorker rapidly filling the work queue until the application runs out of memory and crashes.
👓 @spladug @bsimpson63
> Set a 'maxsize' on the internal work queue in BaseKombuConsumer

- baseplate/diagnostics/tracing/__init__.py
- tests/unit/diagnostics/tracing_tests.py
The 'component' annotation is a standard across
tracing implementations that designates the software
package, framework, or library that generates a given span.
Adding this annotation to Baseplate will make it easier
to see Baseplate-generated spans in a trace.
> Add 'component' annotation to traces

- baseplate/core.py
- baseplate/integration/pyramid/__init__.py
- tests/unit/events/publisher_tests.py
The stuff I merged a couple of weeks ago (#304) has some problems with Pyramid integration. It looks like using `add_request_method(..., reify=True)` leads to a situation where the new request method gets a copy of the underlying Pyramid request object rather than the baseplate-provided wrapper. This means that those methods can't use any context attributes like `secrets` or whatever. This broke things when trying to upgrade GraphQL for canarying.
I poked around a bit and ended up realizing that what I built then was too complicated and instead of trying to wrap the object and do all the `__getattribute__` shenanigans we should go with the mixin approach @bradengroom pioneered in #253. The big difference from that PR remains that we're passing around the `context_config` dictionary rather …
> Simplify the request context laziness setup

- baseplate/server/runtime_monitor.py
- docs/cli/serve.rst
I relented and made this configurable so we can opt services in when Telegraf's ready.
> Make the connection pool stats configurable

- baseplate/observers/tracing.py
Tracing instrumentation is not application-critical. This changes
exception and error logging in the module to 'warning' so non-critical
instrumentation issues do not spam application logs.
> tracing: Turn all exception logging in tracing module to warning

- baseplate/context/memcache/lib.py
- tests/unit/context/memcache_tests.py
This brings the fix to the 0.30.x series to help Thing service upgrade to Python 3.6.
> Backport fix for str/bytes issue in compressed memcache serde

- baseplate/observers/tracing.py
- tests/unit/observers/tracing_tests.py
"Sampled" spans are ones that match a sampled request, which could be at the whim of any number of upstream sampling lotteries. We need a way to differentiate "debug" spans - spans that represent part or all of a request that we have designated specifically as "debug"-required.
Add differentiating between a sampled span and a debug span, and
update TraceObserver to determine whether a span is a debug span
using its flags.
Additionally, add a 'debug' binary annotation to debug spans
for trace storage systems to utilizing in filtering mechanisms.
> baseplate: Add tracing debug tag populating for spans

- baseplate/context/memcache/lib.py
- tests/unit/context/memcache_tests.py
backport of https://github.com/reddit/baseplate.py/pull/339
👓 @spladug @suzie-su
> memcache.lib: Update serializers to handle bytestring values

- baseplate/__init__.py
- baseplate/observers/metrics.py
- baseplate/observers/tracing.py
- docs/api/baseplate/observers/statsd.rst
- tests/unit/observers/metrics_tests.py
- tests/unit/observers/tracing_tests.py
This is a generic interface on spans that allows you to "increment" a tag. The tracing observer just coalesces these into a final tag, while the metrics observer can now listen into these and send counters as well. The idea is that applications can use this interface and not tie themselves to a specific metrics implementation.
This makes it so that an application doing
```python
context.trace.incr_tag("foo")
```
is equivalent to
```python
context.trace.set_tag("counter.foo", "1")
context.metrics.counter("foo").increment()
```
but without the application ever having to know which observers are configured which gives us more flexibility to change observers in the future and keeps application code simpler.
Fixes #305
> Add incr_tag interface to spans for observer-generic counters

- setup.py
We use some types (like typing.NoReturn) that didn't show up until later
point releases.
> Bump minimum required Python version

- baseplate/server/thrift.py
- baseplate/server/wsgi.py
The default was previously 0. I thought that meant wait forever, but
instead it meant die immediately. After fixing graceful shutdown, this
meant we'd still be hard-killing in flight requests but now we'd also be
getting the GreenletExit errors from it. This default of 10 seconds is
meant to give some time for long-running requests while not holding up
shutdown too long.
> Default to 10 second wait for graceful server shutdown

- baseplate/lib/experiments/__init__.py
- baseplate/lib/file_watcher.py
- baseplate/lib/secrets.py
- tests/unit/lib/experiments/experiment_tests.py
Reduce spam in graphql logs caused by excessive retries from secrets and experiments filewatchers.
> Allow backoff value to be set for filewatchers

- baseplate/server/queue_consumer.py
Note, this didn't actually cause the healthchecker to fail, just spam your logs with errors, since the actual request still returns a 200:
```
vagrant@reddit:~/src/super-secret-reddit-service (super-secret-reddit-service)$ curl -v localhost:9400/health
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9400 (#0)
> GET /health HTTP/1.1
> Host: localhost:9400
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Mon, 28 Oct 2019 22:46:58 GMT
< Content-Length: 14
< 
* transfer closed with 14 bytes remaining to read
* stopped the pause stream!
* Closing connection 0
curl: (18) transfer closed with 14 bytes remaining to read
```
> Return List[bytes] in the queue_consumer healthchecker

- baseplate/clients/sqlalchemy.py
- tests/unit/clients/sqlalchemy_tests.py
As part of thing->k8s migration, we noticed that baseplate does not support pool_recycle while creating the db engine.
Added the support for pool_recycle in https://github.snooguts.net/reddit/reddit-service-thing/commit/cc0bbdea642023f5dfc3c6798974596ab5f72f88
We wanted to push the changes to baseplate as well so other services that use pool_recycle do not run into a similar issue when moving to k8s.
👓 @bsimpson63 @spladug
> support pool_recycle in engine_from_config

- baseplate/frameworks/queue_consumer/kafka.py
- docs/api/baseplate/frameworks/queue_consumer/index.rst
- docs/api/baseplate/frameworks/queue_consumer/kafka.rst
- requirements-test.txt
- tests/unit/frameworks/queue_consumer/kafka_tests.py
This lets us run a `QueueConsumerServer` against Kafka instead of kombu/RabbitMQ.
This code is very similar to what has been running in Thing service and Channels service. I'll update the code running in Thing service to match this exactly before merging this baseplate PR.
> queue_consumer: Add Kafka implementation

- baseplate/server/__init__.py
- bin/baseplate-shell
- docs/cli/index.rst
- docs/cli/shell.rst
- setup.py
It turns out that since Apache Thrift, we're standardized on how the
application object works so we can use this shell for both kinds of
services. Not only is this simpler to think about, but it also means
we're not using different configuration parsing for Pyramid shells which
fixes #367.
:eyeglasses: @bradengroom @pacejackson
> Rename baseplate-tshell to baseplate-shell

- baseplate/frameworks/thrift/command.py
The transform was not idempotent when the thriftfile was the same name
as the root module. Staying firmly in hack territory, we just check if
the line we want to transform already has the full path we desire.
(I opted to stay away from f-strings for this patch so that it can be backported to 0.30 more easily)
Fixes #354
> Fix thrift build import rename growing forever on rebuild

- baseplate/observers/sentry.py
When running a script that uses error_reporter_from_config() from a
directory that does not have any git repository, the revision resolution
would infinite loop. This grabs the absolute path to the code before
traversing the tree so that we can truly find out the revision or give
up.
Fixes #177
> Fix infinite loop in Raven setup when using relative paths

- baseplate/server/runtime_monitor.py
- docs/cli/serve.rst
The previous number incorrectly conflated the number of open connections
with the number of in-flight requests. An idle connection has very
little impact on the server, but in-flight requests contend for CPU
time.
Example output:
```
example_server.runtime.reddit.PID2505.open_connections:5|g
example_server.runtime.reddit.PID2505.active_requests:2|g
```
This is a redefinition of the existing `active_requests` gauge. I didn't think it made sense to keep the old one just for backwards compatibility since it was a confusing name. Would it be better to come up with a third name and leave the old one blank instead?
Fixes #353 
:eyeglasses: @pacejackson @bsimpson63
> Rework runtime metrics reporting of concurrency

- baseplate/observers/sentry.py
Support for non-string values was only added in 6.1. Some of our
services are still using older versions.
https://github.com/getsentry/raven-python/blob/master/CHANGELOG.md#610-2017-05-25
> Fix ServerTimeout exemption on raven<6.1

- baseplate/clients/redis.py
- tests/integration/redis_tests.py
This regressed in 1aa93077e24041478b7c38d41c4c65a734bc8e76.
> Fix redis client parameter munging and make test stricter

- baseplate/py.typed
- setup.py
This is just a good citizenship thing. Apparently required per PEP-0561.
https://www.python.org/dev/peps/pep-0561/#packaging-type-information
> Add py.typed file to indicate we support type checking

- baseplate/lib/edge_context.py
- tests/unit/lib/edge_context_tests.py
In authentication service 
2 fields was added into authentication token payload 
1: Scopes(deployed) 
2: Loid(field exists): we are logging more information in this field (PR)
So in order to access those fields easier by other services, add those fields into `property` instead of hiding in the `payload`
@pacejackson @bsimpson63
> Add loid and scopes into AuthenticationToken property

- baseplate/sidecars/secrets_fetcher.py
Allows applications to defined a callback to run after the secret fetcher lays down its file.
test_config.ini
```
[secret-fetcher]
vault.url = http://127.0.0.1:8200
vault.role = my-server-role
output.path = secrets.json
output.owner = vagrant
output.group = vagrant
output.mode = 0400
secrets =
secret/data/dbuser,
secret/data/dbpass
callback = scripts/my-transformer
```
scripts/my-transformer
```
#!/usr/bin/python
import json
import sys
secrets_file = sys.argv[1]
with open(secrets_file) as f:
secrets = json.load(f)
with open('secrets.properties', 'w') as f:
f.write("DB_USER=" + secrets['secrets']['secret/data/dbuser']['data']['value'] + "\n")
f.write("DB_PASS=" + secrets['secrets']['secret/data/dbpass']['data']['value'] + "\n")
```
Running:
```
$ python -m …
```
> Allow custom callback from the secrets fetcher

- tests/integration/thrift_tests.py
This regressed in 86e9948ce3b041eb387ed494b53dd55692382e9d.
The test client pool leaves its connections open, so the test server
would wait around for the whole 10 second default stop timeout. By
setting a short timeout we can end the test much faster. The suite goes
from taking ~120 seconds to ~10 seconds (in CI the difference is ~6 minutes
-> ~4.5 minutes because of the experiments)
> Fix speed regression in thrift integration tests

- baseplate/lib/crypto.py
- baseplate/lib/edge_context.py
Return error early at 2 places to improve performances:
1. In edge context, when the error is jwt.ExpiredSignatureError there's
no point of trying the next version of public key.
2. In message signature verification, if the expiration timestamp is
already in the past there's no point of calculating the digest and do
the comparison.
> Performance fixes

- tests/unit/observers/tracing_tests.py
We didn't seem to have any tests to check this behavior so I added some.
> Add tests for DEBUG and ERROR binary annotations

- baseplate/observers/tracing.py
- tests/unit/observers/tracing_tests.py
Our current system for storing trace data only supports string values for binary annotations so we want to also encode boolean values as lower case strings.
> Convert boolean span tags to strings

- baseplate/sidecars/file_age_watcher.py
This expects a file with configs of:
``file.<name>.dest = <file_location>``
So ideally, the files that you're watching from live-data and secrets fetcher are put in here as entries;
This script will run as a sidecar with all N pods from reddit-service-listing ( or any other service ) and based on the config, it will get the age of the file and send to metrics backend as a histogram.
From here, we can figure out if at least one of the N pods contains a stale file. From here, alert that live-data-fetcher may be faulty.
> Add file-age-watcher that monitors the age of files

- baseplate/lib/metrics.py
- baseplate/observers/metrics.py
Fixup to this pr:
https://github.com/reddit/baseplate.py/pull/400
Many applications access context.metrics directly, which currently throws an error because `context.metrics` is not assigned if the request is not sampled.
> create context.metrics even when request is not sampled

- baseplate/frameworks/queue_consumer/kombu.py
- tests/unit/frameworks/queue_consumer/kombu_tests.py
Current behavior when an error occurs is to requeue the message. This
allows the ability to override that behavior by passing in a function
> Kombu: Add ability to pass in error_handler_fn

- baseplate/frameworks/thrift/__init__.py
- baseplate/observers/metrics.py
- tests/unit/observers/metrics_tests.py
This is required to get proper error handling for observers that use
on_start() to throw an exception to kill the request preemptively, such
as the [upcoming concurrency limiter.][limit]
[limit]: https://github.com/reddit/baseplate.py/compare/master...spladug:active-request-limit
> Thrift: catch exceptions in span.start() as part of flow

- baseplate/lib/metrics.py
- baseplate/observers/metrics.py
- tests/unit/observers/metrics_tests.py
The previous sampling PR failed to account for the fact that some counters are created implicitly by timers. These counters need to know about sampling or telegraf won't be able to compensate for it correctly on the backend.
This should also make sampling more backwards compatible with the old context.metrics syntax by removing the error where context.metrics doesn't exist.
> Add sampling to metrics created by timers

- baseplate/__init__.py
- docs/api/baseplate/index.rst
- tests/unit/core_tests.py
This pattern comes up pretty frequently:
context = baseplate.make_context_object()
with baseplate.make_server_span(context, "foo"):
context.foo.bar()
and while we do need the context object creation and span creation to be separate for different frameworks to have full control of things we can also have some nice sugar for the common case:
with baseplate.server_context("foo") as context:
context.foo.bar()
:eyeglasses: @melissacole @pacejackson
> Add convenience function for creating quick server span contexts

- baseplate/__init__.py
- baseplate/clients/thrift.py
- baseplate/frameworks/thrift/__init__.py
- baseplate/lib/__init__.py
- baseplate/observers/metrics.py
- docs/api/baseplate/index.rst
- tests/integration/thrift_tests.py
This gives services an identity and sends it to downstreams in Thrift
calls. Thrift servers also accept this identity and attach it to the
server span as the peer.service tag.
The idea is to allow servers to get better information about who is
calling them.
> Send and receive service names in Thrift

- baseplate/server/queue_consumer.py
This squelches them outside debug mode but gives applications the
ability to control the logging through the normal Python logging system.
Previously it always went to stderr and was rather spammy.
> Make queue consumer healthchecks go through logging system

- baseplate/server/queue_consumer.py
- tests/unit/server/queue_consumer_tests.py
This brings it in line with the baseplate healthcheck protocol and
allows `baseplate-healthcheck` to work with it.
> Make the queue consumer HTTP healthcheck return JSON

- baseplate/frameworks/queue_consumer/deprecated.py
We used to catch the queue.Empty error and would just 'break' when that happened in get_batch
> Preserve previous behavior of deprecated queue consumer

- baseplate/lib/config.py
- baseplate/observers/timeout.py
- docs/api/baseplate/observers/timeout.rst
They don't make sense in all situations (e.g. cron jobs) and the ideal
is that we explicitly configure them in the future but in the interest
of compatibility we'll just emit a deprecation warning for now.
> Allow disabling server timeouts and disable them by default

- baseplate/lib/thrift_pool.py
- tests/unit/lib/thrift_pool_tests.py
This PR solves another instance of the issue described in #431 (i.e. excess items get into the pool, `thrift_pool.checkedout` returns a negative value).
This time the issue happens when the retry policy exhausted trying to connect to a service. In this case, `self.pool.put(None)` gets called twice: in both `_acquire` and `_release` methods.
Note: I removed two assertions from the `test_max_retry_on_connect` test as they no longer make sense (and fail).
@spladug @m104 Please take a look.
> Thrift pool overflow #2

- baseplate/sidecars/event_publisher.py
This PR updates the event publisher sidecar to print, but not exit on `HTTPUnprocessableEntity` responses from a downstream event collector. This status code is returned when an event cannot be validated by the collector service.
> Updates the event publisher to not exit on validation errors

- baseplate/__init__.py
- baseplate/lib/metrics.py
- baseplate/observers/metrics_tagged.py
- docs/api/baseplate/observers/index.rst
- docs/api/baseplate/observers/tagged_statsd.rst
- docs/conf.py
- setup.py
- tests/integration/message_queue_tests.py
- tests/unit/lib/metrics_tests.py
- tests/unit/observers/metrics_tagged_tests.py
added new metrics observer that forwards tags in influxstatsd format to wavefront, added documentation and tests, retrofitted with sample_rate changes
https://github.com/reddit/baseplate.py/pull/418
> Add support for wavefront tagging to baseplate

- baseplate/lib/thrift_pool.py
- tests/unit/lib/thrift_pool_tests.py
When an exception (other than `queue.Empty`) happens in line 180,
https://github.com/reddit/baseplate.py/blob/887f9be99f367be27d0e58fecdb274cb090a1585/baseplate/lib/thrift_pool.py#L179-L184
it results in a call of
https://github.com/reddit/baseplate.py/blob/887f9be99f367be27d0e58fecdb274cb090a1585/baseplate/lib/thrift_pool.py#L267-L268
which puts an excess item in the queue (above `self.size`).
One of the subsequences of it is:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/baseplate/server/runtime_monitor.py", line 146, in report
reporter(batch)
File "/usr/local/lib/python3.7/dist-packages/baseplate/clients/thrift.py", line 86, in report_runtime_metrics
batch.gauge("pool.in_use").replace(self.pool.checkedout)
File …
```
> Thrift pool overflow #1

- baseplate/thrift/baseplate.thrift
🤦
Also slightly tweak the wording as we could use either string or int
values in the http health checks.
> Fix typo in thrift comment

- baseplate/lib/thrift_pool.py
- tests/unit/lib/thrift_pool_tests.py
Inspired by changes @fishy made to the Thrift Go library ([THRIFT-5214]) and, by proxy, [this blog post] I'm making the Python Thrift library [check if the server is still connected][2] in `TSocket.isOpen()`. This change to Baseplate.py's Thrift pool should be a no-op while Thrift is unchanged, but once Thrift is updated we'll automatically discard connections that are already closed before we try to use them. This costs about a hundred microseconds in tests but means that we don't serialize and send a message just to get an error as soon as we try to read the response so should overall save quite a lot of time. This also means we don't need to retry every thrift call quite as heavily because we're worried about already-dead connections.
[THRIFT-5214]: …
> thrift pool: Discard closed connections when fetching from pool

- baseplate/lib/metrics.py
- docs/guide/faq.rst
- docs/guide/index.rst
- docs/index.rst
I have grand plans for the new "guide" section of the docs.
This fixes #426.
> Add explanation of what to do with "metrics batch too large"

- baseplate/clients/requests.py
- docs/api/baseplate/clients/index.rst
- docs/api/baseplate/clients/requests.rst
- docs/conf.py
- requirements-test.txt
- setup.py
- tests/integration/requests_tests.py
This adds two HTTP clients: 
* The internal client is for use with first-party services and propagates trace and edge context. 
* The external client is for use with third-party services and does not propagate the extra context.
We use @jordanmilne's Advocate library (now updated for modern requests!) to enforce that the internal client only talks to local addresses and the external client only talks to external addresses. The cost of doing this is about 100 microseconds per request.
Fixes #448
> Add requests-based HTTP clients

- baseplate/lib/datetime.py
- tests/unit/lib/datetime_tests.py
This adds an `epoch_milliseconds_to_datetime` function that is intended to be used with the thrift TimestampMilliseconds typedef.
> Add function for converting milliseconds timestamp to datetime
