baseplate/metrics.py, baseplate/thrift_pool.py, tests/unit/metrics_tests.py
These fix #3 and #4. I'll do retries next.
:eyeglasses: @bsimpson63 @kjoconnor
=> Various small improvements

.travis.yml, docs/conf.py, tests/unit/metrics_tests.py, tests/unit/server/server_tests.py
Exactly what it says on the tin. This does a couple of fixups to make a travis-like build environment happy, then adds a travis config to actually do the build.
=> Run tests on Travis CI

baseplate/config.py, baseplate/crypto.py, baseplate/server/__init__.py, baseplate/server/wsgi.py, docs/api/baseplate/config.rst, docs/api/baseplate/crypto.rst, docs/api/index.rst, docs/server.rst, tests/unit/config_tests.py, tests/unit/crypto_tests.py
These are a few additions required for the click tracker and robin projects. I'll be working on event sending from baseplate next as needed for click tracker. Each one is pretty independent, so it might be best to look at individual commits.
:eyeglasses: @florenceyeun @MelissaCole @dellis23
=> Additions for robin and clicktracker

baseplate/config.py, baseplate/context/redis.py, docs/baseplate/context/index.rst, tests/unit/config_tests.py
:eyeglasses: @kjoconnor @dellis23
=> Redis pipelines + bonus

Vagrantfile, manifests/init.pp
👓 @ckwang8128 
cc @spladug for visibility
Guess, check, google, repeat on puppet so feel free to be hard on me!
=> Add Vagrantfile for running tests in development

baseplate/context/cassandra.py
Sorry about that. I should really get some tests on this module :(
:eyeglasses: @pacejackson
=> Fix missed annotate() calls in OpenTracing rename

baseplate/config.py
=> Add optional config example.

baseplate/random.py
👓 @spladug @ckwang8128 
You nerd sniped me.  Couldn't stop thinking about it on the way home.
=> Use bisect for weighted choice implementation.

baseplate/thrift_pool.py, tests/unit/thrift_pool_tests.py
Explanation for this PR: When using Thrift with Java we don't have the benefits of gevent, so to achieve concurrency in requests we use nonblocking server types which have a thread pool for receiving requests and a separate thread pool for processing them. Unfortunately, these servers require the use of a framed/buffered transport since they are processing asynchronously. This poses a problem when using Baseplate libraries/services, since the thread pool assumes the use of a plain TSocket.
I'm open to suggestions on this change - if it would be better to use an alternative method instead of making the change here, that's fine too.
👓  @spladug
=> Allow Thrift connection pool to talk to framed/buffered servers

baseplate/config.py, baseplate/thrift_pool.py, docs/baseplate/config.rst, docs/config_example.ini, tests/unit/config_tests.py
This closes #78 and fixes a small documentation thing I noticed.
:eyeglasses: @ckwang8128 @krishnan-chandra
=> Add percentage config helper and fix docs

baseplate/secrets/__init__.py, baseplate/secrets/fetcher.py, baseplate/secrets/store.py, docs/baseplate/secrets.rst, tests/unit/secrets/store_tests.py
This fixes a couple of small edge cases in the new secrets stuff. See commit messages for more details.
Fixes #98.
=> Fix some edge cases with the SecretsStore

baseplate/file_watcher.py, tests/unit/file_watcher_tests.py
This is a safety net so that if the underlying file becomes completely
corrupt the application can keep on working with stale data.
=> Make FileWatcher use cached data when the underlying file goes bad

baseplate/events/__init__.py, baseplate/events/publisher.py, baseplate/events/queue.py, docs/baseplate/events.rst, docs/words.txt, tests/unit/events/publisher_tests.py
I've updated the docs too, so that should explain everything here. If something's confusing or not sufficiently explained in here please let me know and I'll update the code.
=> Add support for v2 thrift-based events

baseplate/core.py, tests/integration/thrift_tests.py, tests/unit/core_tests.py
Thrift expects a header to be a str in Python 2 (str or bytes works in Python 3) so we `encode` the authentication token in the `AuthenticationContext` constructor so `AuthenticationContext._token` is always `bytes` in Python 3 or `str` in Python 2.  
If we do not do this, the value may be `unicode` in Python 2.  `unicode` works fine as long as the length of the string is under 128 characters but once you go over that, you start to run into errors when Thrift tries to construct the header.
=> Encode Authentication token

baseplate/message_queue.py
The error messages we get from lower level libraries are pretty opaque
and leave the user with nowhere to go. This is intended to give a hint
of where to look next when encountering the error.
=> Add wrapper exceptions for message queue sharp edges

baseplate/context/thrift.py, baseplate/core.py, baseplate/integration/pyramid.py, baseplate/thrift_pool.py, docs/conf.py, setup.cfg, setup.py, tests/unit/crypto_tests.py, tests/unit/events/publisher_tests.py, tests/unit/thrift_pool_tests.py
Remove ignore of E501 in flake8 config and set max line length to 100.
Closes #68
=> Enable E501, set max length to 100

baseplate/metrics.py, tests/unit/metrics_tests.py
* Introduced ``BatchCounter`` class. The main difference between it and the
``Counter`` is that the transport ``send`` method is not called
everytime increment is called. The new class was introduced to maintain
the current ``counter`` API in the ``Client`` implementation.
* The ``Batch`` class now stores a reference to created ``BatchCounter``
instances. These are looked up by counter name and reused when possible.
* The ``send`` method is called on all created ``BatchCounter``
instances during ``Batch.flush``.
Fixes #146
=> Coalesce counters in metrics batchs

baseplate/_compat.py, baseplate/server/healthcheck.py
=> Fix UNIX domain socket healthcheck on Python 3

baseplate/core.py
For service tokens generated by authenticate_service.
Will be used for r2, messenger, others to communicate with thing service for non-request tasks.
👓 @spladug @pacejackson
=> EdgeRequestContextFactory: Add service property

baseplate/thrift_pool.py
In cases where Thrift fails dealing with serialization/deserialization
(such as catastrophically wrong types being passed in) the connection
will end up in a bad state but we'll check it back into the pool to be
reused. This makes it so we close the connection in that case to prevent
it from causing issues for the next user.
(Found this while digging a bit into the "zero bytes" thing. I don't think this is the cause of most of our woes but is definitely a bug in itself)
=> Close thrift connection after unexpected exception in thrift

baseplate/context/memcache/__init__.py, tests/integration/memcache_tests.py
This is an explicit > implicit approach. The wrapped methods of the
memcache pool are now fully redefined. This allows for the spans to be
tagged according to each method being called.
In the future, this should probably be moved "lower" into the client
class to capture just the interactions with the server.
=> Add details to memcache tracing spans

baseplate/events/publisher.py, baseplate/metrics.py, tests/unit/root_tests.py
Remove last references to make_metrics_client and make_tracing_client.
👓 @spladug
=> Remove calls to deprecated functions

baseplate/context/cassandra.py, tests/unit/context/cassandra_tests.py
Prepared statements are only useful if we can re-use them. This change
will cache prepared statements based upon the text of the query being
prepared, and automatically use that cache without preparing a new
statement if an identical statement was already prepared.
One potential gotcha here would be continual memory growth if someone was to prepare a huge number of unique queries. If we think that could be a problem, I can implement a capped LRU cache.
:eyeglasses: @spladug  @prthiaga
=> Automatically cache prepared cassandra statements.

tests/unit/queue_consumer_tests.py
=> Skip queue_consumer_tests if kombu not present.

debian/changelog, setup.py
includes up to e9b48b7aba226b1f596ae8f46f1e63df9303caf4 on master
=> Cut release 0.27.0

baseplate/experiments/providers/simple_experiment.py, baseplate/experiments/targeting/base.py, baseplate/experiments/targeting/tree_targeting.py, tests/unit/experiments/providers/simple_experiment_tests.py, tests/unit/experiments/targeting/tree_targeting_tests.py
Add advanced targeting capabilities to SimpleExperiments.
=> add targeting for SimpleExperiment

baseplate/experiments/providers/simple_experiment.py, tests/unit/experiments/providers/simple_experiment_tests.py
@pacejackson @mattknox @spladug 
I think this should be the last major experiments addition coming into baseplate for the near future.
=> Kaitaan add overrides

baseplate/server/thrift.py, baseplate/server/wsgi.py
There's really no situation in production where we don't want _some_
value for this. This will make development a little more ugly but we can
fix that up in the cookiecutter.
=> Make max_concurrency mandatory for servers

debian/changelog, setup.py
for the v0.28 branch, not master
=> Cut version 0.28.1

baseplate/events/publisher.py
Currently publishers retry indefinitely every two seconds. In the event that collectors become degraded we prefer that clients back off rather than repeatedly retry.
👓 @spladug
=> Add exponential backoff for event publishers

baseplate/secrets/store.py
Don't re-check the secret file on disk multiple times per request
This is a performance improvement and consistency change. For the
lifetime of a single server span, we use the same cached-in-memory copy
of secrets rather than re-checking disk every time and only fetch at all
if we check the secrets. This is better when we read secrets multiple
times per request.
This shows a significant performance improvement when running a
benchmarking script (https://git.io/fpQnW):
Before:
$ python2.7 benchmark-secrets.py
Time elapsed to create 100 spans = 0.9014 seconds (90.14μs / per)
$ python3.4 benchmark-secrets.py
Time elapsed to create 100 spans = 0.9194 seconds (91.94μs / per)
After:
$ python2.7 benchmark-secrets.py
Time elapsed to create 100 spans = 0.0352 seconds (3.52μs / per)
$ python3.4 …
=> Don't re-check the secret file on disk multiple times per request

baseplate/context/cassandra.py, tests/integration/cassandra_tests.py
This fixes a race condition where the server span can complete before
the callback has closed out the child span.
https://github.com/reddit/baseplate/issues/100
👓 @spladug @bradengroom @pacejackson
=>  cassandra: Don't return from result() until callbacks have completed 

baseplate/metrics.py
https://github.com/reddit/baseplate/issues/248
I'm not sure that the max size is set correctly, I got 65507 from https://docstore.mik.ua/manuals/hp-ux/en/B2355-60130/UDP.7P.html
👓 @spladug @pacejackson @bradengroom
=> metrics: Send metrics in batches to avoid a too long message

baseplate/secrets/__init__.py, baseplate/secrets/store.py, docs/secrets.json, tests/unit/secrets/store_tests.py
Add a new secrets type for storing "credentials" (that is a username/password pair).
=> Add CredentialSecrets

baseplate/context/cassandra.py
Fixes https://sentry.reddit.ue1.snooguts.net/sentry/thing-service/issues/310964/
from python-driver:
https://github.com/datastax/python-driver/blob/850f218b5cde1fd000338517372395f690097153/cassandra/concurrent.py#L137
The first commit fixes the error by implementing the missing methods, but doesn't prevent the future from returning and eventually returning the result and closing out the server span. I'm not sure how much we care to worry about that.
The second commit attempts to be a more general purpose fix by wrapping all callbacks so that we don't execute them until the monitoring thread has completed. The tests don't work because it appears that the callbacks are always executed in order and are blocking. I came to this conclusion by adding logging in the callbacks and if there's a …
=> Fix cassandra futures

requirements-docs.txt, requirements-test.txt
GitHub is reporting security vulnerabilities in each. These shouldn't
affect us, but it's good to be up to date anyway.
=> Update some test dependencies

baseplate/experiments/targeting/tree_targeting.py, tests/unit/experiments/targeting/tree_targeting_tests.py
Add support for new comparison operator on experiment targeting.
Supports gt, ge, lt, le, and ne operators
👓 @spladug @mattknox
Recreation of https://github.com/reddit/baseplate/pull/215
=> Add support for more targeting operators

baseplate/diagnostics/tracing/__init__.py
This is just unnecessary noise for application devs 99% of the time.
:eyeglasses: @ckwang8128 @bsimpson63
=> Don't log about where spans are being recorded to

baseplate/context/sqlalchemy.py
> SADeprecationWarning: The ConnectionEvents.dbapi_error() event is deprecated and will be removed in a future release. Please refer to the ConnectionEvents.handle_error() event.
https://docs.sqlalchemy.org/en/13/core/events.html#sqlalchemy.events.ConnectionEvents.handle_error
This will require that we use SQLAlchemy 0.9+.
:eyeglasses: @bsimpson63 @pacejackson
=> Update usage to fix SQLAlchemy deprecation warning

baseplate/core.py
This is just a convenience layer but should help simplify app wire-up
and make it easier to upgrade to future versions with different
observers by just changing config files.
This fixes #311
=> Add a one-stop shop method for configuring diagnostics observers

Makefile
This command will run 'black' and 'reorder-python-imports' for you
=> Add 'fmt' command to Makefile

baseplate/clients/memcache/lib.py, tests/unit/clients/memcache_tests.py
=> memcache.lib: Update serializers to handle bytestring values

baseplate/__init__.py, baseplate/lib/events.py, docs/api/baseplate/lib/events.rst
In the same vein as the improvements from writing the Tutorial, this is stuff that came out of updating the cookiecutter.
=> Minor improvements from upgrading the cookiecutter

baseplate/lib/metrics.py
:thinking: If time were to stop, would we we know?
I think "time" is the incorrect name for what has stopped.  I think it's supposed to be "timer" because it's part of the `Timer` class and the `Timer` class has the `stopped` property.
=> Update error message

baseplate/lib/thrift_pool.py, tests/unit/lib/thrift_pool_tests.py
Fixes #370
:eyeglasses: @pacejackson @eaceaser
=> Rename ThriftConnectionPool's max_retries to max_connection_attempts

baseplate/__init__.py, baseplate/frameworks/thrift/__init__.py, baseplate/observers/metrics.py, baseplate/observers/sentry.py, baseplate/observers/timeout.py, baseplate/observers/tracing.py, baseplate/server/__init__.py, docs/api/baseplate/frameworks/pyramid.rst, docs/api/baseplate/frameworks/queue_consumer/deprecated.rst, docs/api/baseplate/frameworks/queue_consumer/kafka.rst, docs/api/baseplate/frameworks/queue_consumer/kombu.rst, docs/api/baseplate/frameworks/thrift.rst, docs/api/baseplate/index.rst, docs/api/baseplate/lib/events.rst, docs/api/baseplate/observers/index.rst, docs/api/baseplate/observers/statsd.rst, docs/api/baseplate/observers/timeout.rst, docs/tutorial/chapter3/observed.py, docs/tutorial/chapter4/sql.py, tests/integration/timeout_tests.py
The bulk of this is in the final commit. The rest is sorta cleanup/setup. Rather than writing a bunch here, I'd like to see if the new docs do a decent job of explaining. So without further ado, check this out: https://github.com/spladug/baseplate.py/blob/1e45989d8b28a06a60eb460177194fb66c5f226b/docs/api/baseplate/observers/timeout.rst
Fixes #337
:eyeglasses: @pacejackson @eaceaser
=> Request Timeouts

baseplate/server/thrift.py, baseplate/server/wsgi.py
=> Deprecate the max_concurrency setting for Thrift/WSGI servers

baseplate/frameworks/pyramid/__init__.py
Fixes https://github.com/reddit/baseplate.py/issues/394
=> Fix request tracing when a URLDecodeError occurs

LICENSE
This is meant to make it easier to auto-detect our license as BSD
3-clause.
=> Update license language to match upstream BSD 3-clause better

baseplate/__init__.py, docs/api/baseplate/clients/cassandra.rst, docs/api/baseplate/lib/events.rst
=> A couple of doc example fixes

docs/tutorial/chapter2/basic.ini, docs/tutorial/chapter2/index.rst, docs/tutorial/chapter3/observed.ini, docs/tutorial/chapter4/sql.ini
=> Remove max_concurrency from tutorial

baseplate/clients/sqlalchemy.py
=> Add pool_pre_ping option.

baseplate/lib/thrift_pool.py, tests/unit/lib/thrift_pool_tests.py
This update wraps the `ThriftConnectionPool._acquire()` call within a
try/finally block to ensure that the connection slot is returned to the
pool in case a ServerTimeout is raised.
=> Handle ServerTimeouts while connecting to a thrift service

baseplate/frameworks/pyramid/__init__.py, tests/integration/pyramid_tests.py
=> Decode edge payload before passing to edge context factory

baseplate/clients/kombu.py
This PR addresses https://github.com/reddit/baseplate.py/issues/434
👓 @pacejackson
=> Add secrets param to KombuProducer

baseplate/frameworks/pyramid/__init__.py, tests/integration/pyramid_tests.py
=> pyramid: encode edge_payload before setting request.raw_edge_payload

baseplate/frameworks/pyramid/__init__.py, baseplate/server/healthcheck.py, baseplate/thrift/BaseplateService.py, baseplate/thrift/baseplate.thrift, baseplate/thrift/ttypes.py, docs/api/baseplate/clients/thrift.rst, docs/api/baseplate/frameworks/pyramid.rst, docs/cli/healthcheck.rst
Update thrift IDL, healthchecker, and the docs.
=> Baseplate health check v2

docs/api/baseplate/observers/logging.rst
:eyeglasses: @isugimpy 
Fixes #454
=> Add documentation on new JSON structured logging
